require("dotenv").config();
const path = require('path')
const imgPath = path.join(__dirname,'../Images')
console.log(imgPath);

const mongoose = require("mongoose");
const Car = require("./models/car");

const cars = [
  {
    name: "Tesla Model 3",
    category: "Electric",
    type: "Sedan",
    price: 80,
    seats: 4,
    transmission: "Automatic",
    fuel: "Electric",
    image: "/images/Tesla Model 3.webp",
    rating: 4.8,
  },

  {
    name: "BMW X5",
    category: "Luxury",
    type: "SUV",
    price: 120,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/BMW X5.jpeg",
    rating: 4.7,
  },

  {
    name: "Suzuki Ertiga",
    category: "SUV",
    type: "SUV",
    price: 30,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Suzuki-Ertiga.webp",
    rating: 4.0,
  },
  {
    name: "Tesla Model S",
    category: "Electric",
    type: "Sedan",
    price: 120,
    seats: 5,
    transmission: "Automatic",
    fuel: "Electric",
    image: "/images/Tesla Model S.jpeg",
    rating: 4.9,
  },
  {
    name: "Tesla Model X",
    category: "Electric",
    type: "SUV",
    price: 150,
    seats: 7,
    transmission: "Automatic",
    fuel: "Electric",
    image: "/images/Tesla Model X.jpeg",
    rating: 4.8,
  },
  {
    name: "Wagon-R",
    category: "SUV",
    type: "SUV",
    price: 130,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Suzuki-Wagon-R.webp",
    rating: 4.7,
  },
  {
    name: "BMW X7",
    category: "Luxury",
    type: "SUV",
    price: 160,
    seats: 7,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/BMW X7.jpeg",
    rating: 4.8,
  },
  {
    name: "BMW 3 Series",
    category: "Sedan",
    type: "Sedan",
    price: 90,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/BMW 3 Series.jpeg",
    rating: 4.6,
  },
  {
    name: "Audi A4",
    category: "Sedan",
    type: "Sedan",
    price: 85,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Audi-A4.jpeg",
    rating: 4.6,
  },
  {
    name: "Audi Q7",
    category: "Luxury",
    type: "SUV",
    price: 150,
    seats: 7,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Audi Q7.jpeg",
    rating: 4.7,
  },
  {
    name: "Mercedes-Benz C-Class",
    category: "Luxury",
    type: "Sedan",
    price: 110,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Mercedes-Benz C-Class.jpeg",
    rating: 4.8,
  },
  {
    name: "Mercedes-Benz GLE",
    category: "Luxury",
    type: "SUV",
    price: 155,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Mercedes-Benz GLE.jpeg",
    rating: 4.8,
  },
  {
    name: "Toyota Fortuner",
    category: "SUV",
    type: "SUV",
    price: 70,
    seats: 7,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Toyota Fortuner.jpeg",
    rating: 4.5,
  },
  {
    name: "Hyundai Creta",
    category: "SUV",
    type: "SUV",
    price: 55,
    seats: 5,
    transmission: "Manual",
    fuel: "Petrol",
    image: "/images/Hyundai Creta.jpeg",
    rating: 4.4,
  },
  {
    name: "Kia Seltos",
    category: "SUV",
    type: "SUV",
    price: 58,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Kia Seltos.jpeg",
    rating: 4.5,
  },
  {
    name: "Mahindra Thar",
    category: "SUV",
    type: "SUV",
    price: 65,
    seats: 4,
    transmission: "Manual",
    fuel: "Petrol",
    image: "/images/Mahindra Thar.jpeg",
    rating: 4.6,
  },
  {
    name: "Range Rover Sport",
    category: "Luxury",
    type: "SUV",
    price: 200,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Range Rover Sport.jpeg",
    rating: 4.9,
  },
  {
    name: "Jaguar XF",
    category: "Luxury",
    type: "Sedan",
    price: 120,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Jaguar XF.jpeg",
    rating: 4.7,
  },
  {
    name: "Porsche 911",
    category: "Sports",
    type: "Sports",
    price: 250,
    seats: 2,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Porsche 911.jpeg",
    rating: 5.0,
  },
  {
    name: "Lamborghini Huracan",
    category: "Sports",
    type: "Sports",
    price: 350,
    seats: 2,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Lamborghini Huracan.jpeg",
    rating: 5.0,
  },
  {
    name: "Ferrari F8",
    category: "Sports",
    type: "Sports",
    price: 400,
    seats: 2,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Ferrari F8.jpeg",
    rating: 5.0,
  },
  {
    name: "McLaren 720S",
    category: "Sports",
    type: "Sports",
    price: 380,
    seats: 2,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/McLaren 720S.jpeg",
    rating: 4.9,
  },
  {
    name: "Ford Mustang",
    category: "Sports",
    type: "Sports",
    price: 180,
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Ford Mustang.jpeg",
    rating: 4.8,
  },
  {
    name: "Chevrolet Camaro",
    category: "Sports",
    type: "Sports",
    price: 170,
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Chevrolet Camaro.jpeg",
    rating: 4.7,
  },
  {
    name: "Nissan GT-R",
    category: "Sports",
    type: "Sports",
    price: 300,
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Nissan GT-R.jpeg",
    rating: 4.9,
  },
  {
    name: "Toyota Camry",
    category: "Sedan",
    type: "Sedan",
    price: 75,
    seats: 5,
    transmission: "Automatic",
    fuel: "Hybrid",
    image: "/images/Toyota Camry.jpeg",
    rating: 4.6,
  },

  {
    name: "Honda City",
    category: "Sedan",
    type: "Sedan",
    price: 50,
    seats: 5,
    transmission: "Manual",
    fuel: "Petrol",
    image: "/images/Honda City.jpeg",
    rating: 4.4,
  },
  {
    name: "Skoda Slavia",
    category: "Sedan",
    type: "Sedan",
    price: 52,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Skoda Slavia.jpeg",
    rating: 4.5,
  },
  {
    name: "Volkswagen Virtus",
    category: "Sedan",
    type: "Sedan",
    price: 54,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Volkswagen-virtus.webp",
    rating: 4.5,
  },
  {
    name: "Hyundai Verna",
    category: "Sedan",
    type: "Sedan",
    price: 53,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Hyundai Verna.jpeg",
    rating: 4.4,
  },
  {
    name: "BYD Atto 3",
    category: "Electric",
    type: "SUV",
    price: 95,
    seats: 5,
    transmission: "Automatic",
    fuel: "Electric",
    image: "/images/BYD Atto 3.jpeg",
    rating: 4.6,
  },
  {
    name: "MG ZS EV",
    category: "Electric",
    type: "SUV",
    price: 85,
    seats: 5,
    transmission: "Automatic",
    fuel: "Electric",
    image: "/images/MG ZS EV.jpeg",
    rating: 4.5,
  },
  {
    name: "Tata Nexon EV",
    category: "Electric",
    type: "SUV",
    price: 60,
    seats: 5,
    transmission: "Automatic",
    fuel: "Electric",
    image: "/images/Tata Nexon EV.jpeg",
    rating: 4.6,
  },
  {
    name: "Kia EV6",
    category: "Electric",
    type: "SUV",
    price: 140,
    seats: 5,
    transmission: "Automatic",
    fuel: "Electric",
    image: "/images/Kia EV6.jpeg",
    rating: 4.8,
  },
  {
    name: "Audi e-tron",
    category: "Electric",
    type: "SUV",
    price: 160,
    seats: 5,
    transmission: "Automatic",
    fuel: "Electric",
    image: "/images/Audi e-tron.jpeg",
    rating: 4.8,
  },
  {
    name: "Mercedes EQS",
    category: "Electric",
    type: "Sedan",
    price: 200,
    seats: 5,
    transmission: "Automatic",
    fuel: "Electric",
    image: "/images/Mercedes EQS.jpeg",
    rating: 4.9,
  },
  {
    name: "Volvo XC90",
    category: "Luxury",
    type: "SUV",
    price: 145,
    seats: 7,
    transmission: "Automatic",
    fuel: "Hybrid",
    image: "/images/Volvo XC90.jpeg",
    rating: 4.7,
  },
  {
    name: "Volvo S90",
    category: "Luxury",
    type: "Sedan",
    price: 120,
    seats: 5,
    transmission: "Automatic",
    fuel: "Hybrid",
    image: "/images/Volvo S90.webp",
    rating: 4.7,
  },
  {
    name: "Jeep Compass",
    category: "SUV",
    type: "SUV",
    price: 65,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Jeep Compass.webp",
    rating: 4.4,
  },
  {
    name: "Jeep Wrangler",
    category: "SUV",
    type: "SUV",
    price: 150,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Jeep Wrangler.webp",
    rating: 4.7,
  },
  {
    name: "Toyota Land Cruiser",
    category: "Luxury",
    type: "SUV",
    price: 220,
    seats: 7,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Toyota Land Cruiser.webp",
    rating: 4.9,
  },
  {
    name: "Bentley Continental GT",
    category: "Luxury",
    type: "Sports",
    price: 450,
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Bentley Continental GT.webp",
    rating: 5.0,
  },
  {
    name: "Rolls Royce Ghost",
    category: "Luxury",
    type: "Sedan",
    price: 500,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Rolls Royce Ghost.webp",
    rating: 5.0,
  },
  {
    name: "Aston Martin DB11",
    category: "Sports",
    type: "Sports",
    price: 420,
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Aston Martin DB11.webp",
    rating: 4.9,
  },
  {
    name: "Bugatti Chiron",
    category: "Sports",
    type: "Sports",
    price: 800,
    seats: 2,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Bugatti Chiron.webp",
    rating: 5.0,
  },
  {
    name: "Pagani Huayra",
    category: "Sports",
    type: "Sports",
    price: 900,
    seats: 2,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Pagani Huayra.webp",
    rating: 5.0,
  },
  {
    name: "Tata Harrier",
    category: "SUV",
    type: "SUV",
    price: 60,
    seats: 5,
    transmission: "Manual",
    fuel: "Petrol",
    image: "/images/Tata Harrier.webp",
    rating: 4.4,
  },
  {
    name: "Mahindra XUV700",
    category: "SUV",
    type: "SUV",
    price: 68,
    seats: 7,
    transmission: "Automatic",
    fuel: "Petrol",
    image: "/images/Mahindra XUV700.webp",
    rating: 4.6,
  },
  {
    name: "Honda Accord",
    category: "Sedan",
    type: "Sedan",
    price: 85,
    seats: 5,
    transmission: "Automatic",
    fuel: "Hybrid",
    image: "/images/Honda Accord.webp",
    rating: 4.6,
  },
  {
    name: "Lexus ES300h",
    category: "Luxury",
    type: "Sedan",
    price: 130,
    seats: 5,
    transmission: "Automatic",
    fuel: "Hybrid",
    image: "/images/Lexus ES300h.webp",
    rating: 4.8,
  },
];

mongoose.connect(process.env.MONGO_URI).then(async () => {
  console.log("MongoDB Connected");

  await Car.deleteMany(); // clears old data
  await Car.insertMany(cars);

  console.log("Cars Added ✅");

  process.exit();
});
